+incdir+tb/env
+incdir+tb/interfaces
+incdir+tb/pkg
+incdir+tb/agents/fe
+incdir+tb/agents/be
+incdir+tb/agents/cosim
+incdir+tb/modified_agents/fe
+incdir+tb/modified_agents/cache

tb/pkg/mock_rtl_pkg.sv
tb/interfaces/fe_if.sv
tb/interfaces/lsu_if.sv
tb/interfaces/be_if.sv
tb/interfaces/ob_if.sv
tb/interfaces/ob_cosim_if.sv
tb/interfaces/getter_if.sv
tb/modified_agents/cache/lsu_if.sv
tb/modified_agents/fe/orbe_fe_if.sv
tb/pkg/isa_cosim_dpi_pkg.sv
tb/pkg/be_tb_pkg.sv
tb/top/mock_rtl.sv
tb/top/mock_obs_probe.sv
tb/top/rtl_v1_obs_probe.sv
tb/top/rtl_v1_wrapper.sv
tb/top/be_tb_top.sv
