// Product-neutral handoff records between the ORBE COSIM observation sampler
// and the COSIM adapter. No RTL, BETA, or P600 type is used here.
package orbe_cosim_obs_pkg;
  localparam int unsigned COSIM_ARF_REG_NUM = 32;
  localparam int unsigned COSIM_CSR_STATE_NUM = 16;
  localparam int unsigned ORBE_RECOVERY_KIND_W = 3;

  // Keep these values equal to rtl/rtl_v1/pkg/or_be_types_pkg.sv
  // recovery_kind_e. Verification code uses this enum so mock runs do not
  // need to import the real RTL package.
  typedef enum logic [ORBE_RECOVERY_KIND_W-1:0] {
    ORBE_RECOVERY_MISPREDICT = 3'd0,
    ORBE_RECOVERY_EXCEPTION  = 3'd1,
    ORBE_RECOVERY_MRET       = 3'd2,
    ORBE_RECOVERY_INTERRUPT  = 3'd3,
    ORBE_RECOVERY_FENCE_I    = 3'd4,
    ORBE_RECOVERY_SRET       = 3'd5
  } orbe_recovery_kind_e;

  typedef enum logic [1:0] {
    COSIM_EVENT_COMMIT    = 2'd0,
    COSIM_EVENT_MEM_STORE = 2'd1,
    COSIM_EVENT_DUT_EXIT  = 2'd2,
    // Internal mailbox delimiter. This is generated by be_agent and is not
    // an RTL observation signal or a cycle counter carried by ob_cosim_if.
    COSIM_EVENT_CYCLE_END = 2'd3
  } cosim_event_kind_t;

  typedef struct packed {
    cosim_event_kind_t kind;
    logic [31:0] group;
    logic [63:0] pc;
    logic [63:0] rob_idx;
    logic [63:0] order;
    logic [63:0] vaddr;
    logic [63:0] data;
    logic [7:0]  mask;
    logic        terminal;
  } cosim_commit_event_t;

  // Architectural state is sampled separately from commit tickets. A single
  // event represents the post-boundary state after all commit groups from the
  // sampled cycle have been consumed by the adapter.
  typedef struct packed {
    logic [COSIM_ARF_REG_NUM-1:0][63:0] int_arf;
    logic [COSIM_ARF_REG_NUM-1:0][63:0] fp_arf;

    logic                               csr_valid;
    logic [COSIM_CSR_STATE_NUM-1:0]     csr_state_valid;
    logic [COSIM_CSR_STATE_NUM-1:0][11:0] csr_state_addr;
    logic [COSIM_CSR_STATE_NUM-1:0][63:0] csr_state;

    logic        csr_event_valid;
    logic [11:0] csr_event_addr;
    logic [63:0] csr_event_wdata;
    logic [63:0] csr_event_rdata;
  } cosim_arch_state_event_t;
endpackage
