// Product-neutral handoff records between the ORBE COSIM observation sampler
// and the COSIM adapter. No RTL, BETA, or P600 type is used here.
package orbe_cosim_obs_pkg;
  localparam int unsigned COSIM_ARF_REG_NUM = 32;
  localparam int unsigned COSIM_CSR_STATE_NUM = 16;
  localparam int unsigned ORBE_RECOVERY_KIND_W = 3;

  // Keep these values equal to recovery_kind_e in the backend RTL types
  // package (or_be_types_pkg.sv).  Verification code uses this enum so mock
  // runs do not need to import the real RTL package.
  typedef enum logic [ORBE_RECOVERY_KIND_W-1:0] {
    ORBE_RECOVERY_MISPREDICT = 3'd0,
    ORBE_RECOVERY_EXCEPTION  = 3'd1,
    ORBE_RECOVERY_MRET       = 3'd2,
    ORBE_RECOVERY_INTERRUPT  = 3'd3,
    ORBE_RECOVERY_FENCE_I    = 3'd4,
    ORBE_RECOVERY_SRET       = 3'd5
  } orbe_recovery_kind_e;

  typedef enum logic [2:0] {
    COSIM_EVENT_COMMIT    = 3'd0,
    COSIM_EVENT_MEM_STORE = 3'd1,
    COSIM_EVENT_DUT_EXIT  = 3'd2,
    // Internal mailbox delimiter. This is generated by be_agent and is not
    // an RTL observation signal or a cycle counter carried by ob_cosim_if.
    COSIM_EVENT_CYCLE_END = 3'd3,
    COSIM_EVENT_RECOVERY  = 3'd4
  } cosim_event_kind_t;

  typedef struct packed {
    cosim_event_kind_t kind;
    logic [31:0] group;
    logic [63:0] pc;
    logic [63:0] rob_idx;
    logic [63:0] order;
    logic [63:0] vaddr;
    logic [63:0] data;
    logic [7:0]  mask;
    logic        terminal;
    logic [63:0] result;
    logic [4:0]  rd_idx;
    logic        rd_is_fp;
    logic        rd_write_enable;
    logic [4:0]  fflags;
    logic [62:0] exception_cause;
    logic [63:0] exception_tval;
    logic        exception_valid;
    logic        commit_valid;
    logic        redirect_valid;
    logic [2:0]  recovery_kind;
    logic [63:0] redirect_pc;
    logic signed [63:0] mnemonic;
    logic [63:0] ref_result;
    logic [63:0] ref_pc;
    logic [4:0] ref_rd_idx;
    logic ref_rd_is_fp;
    logic [62:0] ref_exception_cause;
    logic [63:0] ref_exception_tval;
    logic [2:0] ref_recovery_kind;
    logic [63:0] ref_redirect_pc;
    logic level2_mismatch;
  } cosim_commit_event_t;

  // Architectural state is sampled separately from commit tickets. A single
  // event represents the post-boundary state after all commit groups from the
  // sampled cycle have been consumed by the adapter.
  typedef struct packed {
    logic [COSIM_ARF_REG_NUM-1:0][63:0] int_arf;
    logic [COSIM_ARF_REG_NUM-1:0][63:0] fp_arf;

    logic                               csr_valid;
    logic [COSIM_CSR_STATE_NUM-1:0]     csr_state_valid;
    logic [COSIM_CSR_STATE_NUM-1:0][11:0] csr_state_addr;
    logic [COSIM_CSR_STATE_NUM-1:0][63:0] csr_state;

    logic        csr_event_valid;
    logic [11:0] csr_event_addr;
    logic [63:0] csr_event_wdata;
    logic [63:0] csr_event_rdata;
  } cosim_arch_state_event_t;

  typedef struct packed {
    logic [63:0] pc;
    logic [31:0] inst_bits;
    logic is_compressed;
    logic [4:0] rs1_idx;
    logic [4:0] rs2_idx;
    logic [4:0] rs3_idx;
    logic [4:0] rd_idx;
    logic rs1_is_fp;
    logic rs2_is_fp;
    logic rs3_is_fp;
    logic rd_is_fp;
    logic use_rs1;
    logic use_rs2;
    logic use_rs3;
    logic use_rd;
    logic is_store;
    logic [2:0] mem_funct3;
    logic imm_valid;
    logic [63:0] imm_data;
    logic [23:0] exe_subop;
    logic is_serial;
    logic is_fp_instruction;
    logic is_atomic;
    logic dec_is_fp_opcode;
    logic [16:0] full_decode;
  } cosim_decode_pld_t;

  typedef struct packed {
    logic [63:0] rs1_data;
    logic [63:0] rs2_data;
    logic [1:0] fu_group;
    logic imm_valid;
    logic [63:0] imm_data;
    logic [63:0] pc;
    logic [31:0] inst_bits;
    logic is_compressed;
    logic pred_taken;
    logic [63:0] pred_target_pc;
    logic [63:0] self_tag;
    logic [23:0] exe_subop;
    logic [16:0] full_decode;
    logic fetch_excp_vld;
    logic [4:0] fetch_excp_cause;
    logic [63:0] fetch_excp_tval;
  } cosim_isq_g0_issue_pld_t;

  typedef struct packed {
    logic [63:0] rs1_data;
    logic [63:0] rs2_data;
    logic [63:0] imm_data;
    logic [63:0] self_tag;
    logic [1:0] fu_group;
    logic [23:0] exe_subop;
  } cosim_isq_g1_issue_pld_t;

  typedef struct packed {
    logic [63:0] rs1_data;
    logic [63:0] rs2_data;
    logic [63:0] rs3_data;
    logic [63:0] self_tag;
    logic [23:0] exe_subop;
    logic [16:0] full_decode;
  } cosim_isq_g2_issue_pld_t;

  typedef struct packed {
    logic [63:0] rs1_data;
    logic [63:0] store_data;
    logic [63:0] imm_data;
    logic [63:0] self_tag;
    logic imm_valid;
    logic [2:0] mem_funct3;
    logic rd_is_fp;
    logic [23:0] exe_subop;
  } cosim_isq_g3_issue_pld_t;
endpackage
