`ifndef OR_BE_TYPES_PKG_SV
`define OR_BE_TYPES_PKG_SV

// OR-BE backend types.
//
// Scope: exactly the cross-stage schema that 集成层.md §2.2 freezes plus the
// event batches that more than one module doc names.  Nothing here is invented:
// every field and width traces to a microarchitecture document, and anything
// already frozen elsewhere is imported rather than restated.
//
//   exe_subop / G3 classification      exe_subop_pkg.sv          (frozen)
//   LSU payloads, tag width, capacity  or_be_lsu_protocol_pkg.sv (frozen)
//
// 集成层.md §2.2 freezes widths and encodings only, not packed field order, so
// the orders below are a local choice.  The total widths are checked against
// the documented 372 / 556 by or_be_types_check.sv.
package or_be_types_pkg;

    import exe_subop_pkg::*;
    import or_be_lsu_protocol_pkg::*;

    // ---------------------------------------------------------------------
    // Machine constants
    // ---------------------------------------------------------------------

    // Architectural register width.
    localparam int XLEN = 64;

    // FP register width.  RV64 with D means FLEN == XLEN == 64; they are
    // separate concepts that happen to agree, same as XLEN vs LSU_DATA_W.
    localparam int FLEN = 64;

    // ROB / SCB slot handle.  The LSU contract froze it at 4 bits and a tag is
    // the slot number itself, so the two are the same quantity -- take the
    // frozen one rather than declaring a second 4.
    localparam int TAG_W      = LSU_TAG_W;
    localparam int ROB_DEPTH  = 1 << TAG_W;              // 16

    // IB pointers are {loopbit, index[2:0]} (IB微架构文档 ⑤).
    localparam int IB_DEPTH   = 8;
    localparam int IB_PTR_W   = $clog2(IB_DEPTH) + 1;    // 4

    // SCB pointers are 5-bit {loopbit, index[3:0]} (CompletionScoreboard ⑤).
    localparam int ROB_PTR_W  = TAG_W + 1;               // 5

    localparam int REG_ADDR_W = 5;
    localparam int NUM_GPR    = 32;
    localparam int NUM_FPR    = 32;

    // Two dispatch slots and two retire lanes; four completion lanes.
    localparam int ISSUE_WIDTH = 2;
    localparam int NUM_LANES   = 4;

    // How many instructions retired this cycle: 0..ISSUE_WIDTH, so the
    // width is clog2(ISSUE_WIDTH+1), NOT ISSUE_WIDTH-1:0.  Those two happen
    // to both be 2 bit today -- arithmetic coincidence, not meaning.
    localparam int COMMIT_COUNT_W = $clog2(ISSUE_WIDTH + 1);

    // Architectural register-file read ports.  Shapes frozen by 集成层 §2.5(1):
    // the source number *is* the index and its base is 1, not 0 -- there is no
    // `rs0`.  Every module that carries these ports declares them identically:
    //
    //   INT   [ISSUE_WIDTH][1:INT_SRC_PER_SLOT]   (s,x), s in {0,1}, x in {1,2}
    //   FP    [1:FP_READ_PORTS]                   x in {1,2,3}, no slot dimension
    //
    // Do NOT flatten the INT ports to [4]: flattening makes slot-major vs
    // source-major a second unowned choice, and S2 showed independent agents
    // pick differently when a choice is left unowned.
    localparam int INT_SRC_PER_SLOT = 2;
    localparam int INT_READ_PORTS   = ISSUE_WIDTH * INT_SRC_PER_SLOT;   // 4
    localparam int FP_READ_PORTS    = 3;

    // rs_data_sel_t -- one-hot0 source select, 集成层 §2.5(2) freezes the bit
    // order.  Generated by dependency_check, decoded by the §2.1 assembly; both
    // sides must read the same order or the wrong lane is taken silently.
    //   [6]    sel_arf
    //   [5:4]  sel_commit[1:0]     bit4 = commit lane 0
    //   [3:0]  sel_bypass[3:0]     bit0 = bypass lane 0
    // No typedef here on purpose: `rs_data_sel_t` is the *signal* name the docs
    // use (dependency_check ⑥, 集成层 §2.1), so a type of that name would shadow
    // the port in every module that imports this package.
    localparam int RS_DATA_SEL_W = 1 + ISSUE_WIDTH + NUM_LANES;         // 7

    // FU index *within* a group, not a global group id (集成层 §2.2).
    localparam int FU_GROUP_W = 2;

    // How many FUs each issue group holds -- 集成层 §1.2 ("G0 三位、G1 两位、
    // G2 一位") and §2.5(6).  This is a *count*, not an index width: do not
    // reach for FU_GROUP_W or ISSUE_WIDTH to size a per-requester array just
    // because the number happens to match.
    //   G0  ALU0/BRU, CSR, DIV
    //   G1  ALU1, MUL
    //   G2  FPU        -- single member, no arbiter, completion drives lane 2
    //   G3  LSU        -- outside the DUT, no arbiter, drives lane 3
    localparam int G0_NUM_FU = 3;
    localparam int G1_NUM_FU = 2;
    localparam int G2_NUM_FU = 1;

    // Each FU's identity *within* its group.  This is what a FU compares
    // `FU_Group` against to decide "is this issue for me", and what the top
    // level uses to wire FU k to the arbiter's req_*[k].  A count is not an
    // identity -- G0_NUM_FU says how many, these say which.
    //
    // Note ALU is 0 in both groups: alu_simple is instantiated twice, as
    // ALU0/BRU in G0 and ALU1 in G1 (FU接入契约 §1.1).
    localparam int G0_FU_ALU = 0;
    localparam int G0_FU_CSR = 1;
    localparam int G0_FU_DIV = 2;
    localparam int G1_FU_ALU = 0;
    localparam int G1_FU_MUL = 1;

    localparam int MEM_FUNCT3_W = LSU_MEM_F3_W;          // 3, frozen
    localparam int EXE_SUBOP_W  = BACKEND_EXE_SUBOP_W;   // 24, frozen

    // SCB carries a 63-bit cause field; the LSU boundary is 5-bit and
    // zero-extends into it (lsu微架构文档 ④#3).
    // CSR address field.  RISC-V fixes it at 12 bit.  It also happens to equal
    // FULL_DECODE_W-5 because full_decode packs it in the low bits, but that is
    // arithmetic coincidence, not meaning -- name the quantity.
    localparam int CSR_ADDR_W = 12;

    localparam int EXCP_CAUSE_W = 63;

    // Payload-side fetch-exception cause.  **Deliberately not EXCP_CAUSE_W.**
    // EXCP_CAUSE_W is 63 because a completion lane carries mcause[62:0]; the
    // front end can only ever report an architectural fetch cause (1 =
    // instruction access fault, 12 = instruction page fault, ...), all of
    // which fit in 5 bits, and `fe_be_instr_pld_t.exception_cause` in the TB
    // is 5 bits for the same reason.  Carrying 63 bits of a 0..31 value
    // through two payload stages would cost 116 bit of IB+ISQ payload for
    // nothing.  alu_simple zero-extends to EXCP_CAUSE_W when it drives the
    // completion lane.
    localparam int FETCH_EXCP_CAUSE_W = 5;
    localparam int FFLAGS_W     = 5;
    localparam int FULL_DECODE_W = 17;
    localparam int RECOVERY_KIND_W = 3;

    // Privilege level encoding.  RISC-V fixes it at 2 bit (mstatus.MPP and
    // system_instruction_handler ⑥ current_priv(2)); M-only here, so the only
    // value in flight is 2'b11.
    localparam int PRIV_W = 2;

    // isa_pkg_v3.md · priv_e —— 由 registry 生成（rtl-generation_v3.md §2.1）。
    typedef enum logic [PRIV_W-1:0] {
        PRIV_U = 2'b00,
        PRIV_S = 2'b01,
        PRIV_M = 2'b11
    } priv_e;

    // isa_pkg_v3.md · exception_cause_e —— 同步异常的 cause 编号，不带中断标志位。
    typedef enum logic [EXCP_CAUSE_W-1:0] {
        EXCP_INSTR_ACCESS_FAULT       = EXCP_CAUSE_W'(1),
        EXCP_ILLEGAL_INSTRUCTION      = EXCP_CAUSE_W'(2),
        EXCP_BREAKPOINT               = EXCP_CAUSE_W'(3),
        EXCP_LOAD_ADDR_MISALIGNED     = EXCP_CAUSE_W'(4),
        EXCP_LOAD_ACCESS_FAULT        = EXCP_CAUSE_W'(5),
        EXCP_STORE_AMO_ADDR_MISALIGNED = EXCP_CAUSE_W'(6),
        EXCP_STORE_AMO_ACCESS_FAULT   = EXCP_CAUSE_W'(7),
        EXCP_ECALL_FROM_U             = EXCP_CAUSE_W'(8),
        EXCP_ECALL_FROM_S             = EXCP_CAUSE_W'(9),
        EXCP_ECALL_FROM_M             = EXCP_CAUSE_W'(11)
    } exception_cause_e;

    // XLEN and the LSU data width are separate concepts that happen to agree.
    // If they ever diverge the payload assembly below is wrong, so pin it.
    localparam bit XLEN_MATCHES_LSU_DATA_W = (XLEN == LSU_DATA_W);

    typedef logic [XLEN-1:0]       xlen_t;
    typedef logic [TAG_W-1:0]      rob_tag_t;
    typedef logic [ROB_PTR_W-1:0]  rob_ptr_t;
    typedef logic [REG_ADDR_W-1:0] reg_addr_t;

    // ---------------------------------------------------------------------
    // full_decode -- 集成层 §2.2
    // ---------------------------------------------------------------------
    //   [16]    csr_write_intent
    //   [15]    illegal
    //   [14:12] rm
    //   [11:0]  csr_addr
    typedef enum logic [2:0] {
        RM_RNE = 3'b000,
        RM_RTZ = 3'b001,
        RM_RDN = 3'b010,
        RM_RUP = 3'b011,
        RM_RMM = 3'b100,
        RM_RSV5 = 3'b101,   // reserved
        RM_RSV6 = 3'b110,   // reserved
        RM_DYN = 3'b111     // FPU takes SIH's frm at issue
    } rm_e;

    typedef struct packed {
        logic        csr_write_intent;
        logic        illegal;
        rm_e         rm;
        logic [11:0] csr_addr;
    } full_decode_t;

    function automatic logic rm_is_reserved(input rm_e rm);
        return (rm == RM_RSV5) || (rm == RM_RSV6);
    endfunction

    // ---------------------------------------------------------------------
    // IB_Payload -- 232 bit (IB微架构文档 ⑤)
    // ---------------------------------------------------------------------
    // **队列里存的就是 FE 送进来的那 8 个字段，逐位相同，一个不多一个不少。**
    //
    // 也就是说 **FE -> IB 是纯连线**：这条路径上没有 RVC 展开，没有译码，
    // 没有任何判断，连 fetch_excp 的清零掩码都没有。约束来自实测——2026-08-26
    // 确认取指拍（FE 的 flop -> IB 的 flop）连一块 RVC 展开都放不下，所以
    // **任何与译码相关的逻辑都必须在 IB 之后**（P1译码位置重构分析.md 形态 A；
    // 形态 B2 的「入队侧展开一次」因此作废）。
    //
    // 出队侧两条分支并行：
    //   地址支  raw -> [RVC 展开的寄存器选择锥] -> rs/rd -> ARF / tag_mapping 读
    //   译码支  raw -> [RVC 展开 -> 全译码] -> decoded_info_t
    // 两条共用**同一个**展开器实例：地址支只读它输出的 20 位固定切片，综合会把
    // 立即数与 opcode 那些深锥从这条路径上剪掉，剩下的就是浅的寄存器选择 mux 树。
    // 所以不需要第二份「寄存器号提取」实现，也就没有同源风险。
    //
    // 372 -> 232 省下的正是那 140 位译码产物：120 位进 decoded_info_t，
    // 20 位的寄存器索引不再存——它们是展开结果的固定切片，出队侧现算。
    //
    // `inst_bits` 是 **RAW 形态**，与 FE 送的逐位相同（压缩指令是
    // `{16'b0, 原始半字}`）。非法指令的 mtval 必须是程序里真实存在的那个编码，
    // 展开结果不是程序里的东西。ISQ_Payload 直接透传它，所以四个 FU 的 tval
    // 逻辑一行都不用改。
    //
    // 字段集与 fe_be_protocol_pkg::fe_be_instr_pld_t 相同，宽度相等由
    // or_be_types_check 钉住（本包不能 import 那个包——依赖方向是反的）。
    typedef struct packed {
        // instruction identity
        xlen_t              pc;
        logic [31:0]        inst_bits;
        logic               is_compressed;
        // branch prediction
        logic               pred_taken;
        xlen_t              pred_target_pc;
        // fetch-side exception (decode微架构文档 ④#7)
        // Set when the front end could not fetch this PC at all.  `inst_bits`
        // is then meaningless, so decode forces this entry onto G0 with no
        // sources and no destination -- see decode.sv.
        logic                            fetch_excp_vld;
        logic [FETCH_EXCP_CAUSE_W-1:0]   fetch_excp_cause;
        xlen_t                           fetch_excp_tval;
    } ib_payload_t;

    localparam int IB_PAYLOAD_W = $bits(ib_payload_t);

    // ---------------------------------------------------------------------
    // decoded_info -- 120 bit，decode 在**出队侧**产生的全部译码产物
    // ---------------------------------------------------------------------
    // **这里没有 rs*_idx / rd_idx。** 它们是出队侧展开器输出 `inst32` 的固定切片，
    // 由 backend_top 的胶水直接切出去送寄存器读，**不经过 decode** —— 这正是
    // "寄存器读提前起跑"的全部内容：地址路径只等展开器的寄存器选择锥（浅），
    // 不等全译码（深）。
    //
    // 索引**不被 ④#6 的 illegal 清零门控**，这是与 372 位时代唯一的语义差别。
    // 安全性由消费者侧保证，逐条核过：
    //   dependency_check ④#1  rd_write_enable = use_rd && ...   → use_rd 主导
    //   dependency_check ④#3  slot1_dep_hit 受 rd_write_enable[SLOT0]
    //                         与 use_rs[SLOT1][x] 双重限定
    //   INT/FP_tag_mapping    alloc 由 rd_write_enable 门控
    //   ARF / tag_mapping 读  组合读无副作用，输出被 use_rs* 掩掉
    //   isq_payload_t         根本不带索引
    typedef struct packed {
        logic               is_serial;
        logic               is_fp_instruction;
        // sources -- 只有限定位，索引见上
        logic               use_rs1;
        logic               use_rs2;
        logic               use_rs3;
        logic               rs1_is_fp;
        logic               rs2_is_fp;
        logic               rs3_is_fp;
        // destination
        logic               use_rd;
        logic               rd_is_fp;
        // memory sideband (G3 only)
        logic               is_store;          // plain store only
        logic [MEM_FUNCT3_W-1:0] mem_funct3;
        // immediate: already fully sign-extended by decode
        logic               imm_valid;
        logic signed [XLEN-1:0] imm_data;
        // decode results
        backend_exe_subop_t exe_subop;
        full_decode_t       full_decode;
    } decoded_info_t;

    localparam int DECODED_INFO_W = $bits(decoded_info_t);

    // ---------------------------------------------------------------------
    // ISQ_Payload -- 556 bit (集成层 §2.1 is its only schema definition)
    // ---------------------------------------------------------------------
    // Assembly-side overwrite: full_decode.rm is replaced by dispatch_logic's
    // effective_rm before entering the payload; the other 14 bits pass through.
    typedef struct packed {
        // operands
        xlen_t     rs1_data;
        xlen_t     rs2_data;
        xlen_t     rs3_data;
        logic      rs1_ready;
        logic      rs2_ready;
        logic      rs3_ready;
        rob_tag_t  rs1_wait_tag;
        rob_tag_t  rs2_wait_tag;
        rob_tag_t  rs3_wait_tag;
        // routing
        rob_tag_t              self_tag;
        logic [FU_GROUP_W-1:0] fu_group;
        // immediate
        logic      imm_valid;
        logic signed [XLEN-1:0] imm_data;
        // instruction identity + prediction
        xlen_t       pc;
        logic [31:0] inst_bits;
        logic        is_compressed;
        logic        pred_taken;
        xlen_t       pred_target_pc;
        // memory sideband
        logic                    is_store;
        logic [MEM_FUNCT3_W-1:0] mem_funct3;
        logic                    rd_is_fp;
        // decode results
        backend_exe_subop_t exe_subop;
        full_decode_t       full_decode;
        // fetch-side exception -- passes through unchanged from IB_Payload
        logic                            fetch_excp_vld;
        logic [FETCH_EXCP_CAUSE_W-1:0]   fetch_excp_cause;
        xlen_t                           fetch_excp_tval;
    } isq_payload_t;

    localparam int ISQ_PAYLOAD_W = $bits(isq_payload_t);

    // ---------------------------------------------------------------------
    // completion_common -- the shape all four lanes drive
    // ---------------------------------------------------------------------
    // Lane constraints (集成层 §1.2, CompletionScoreboard ⑥):
    //   G1  event fields all zero
    //   G2  exception / mispredict / is_mret / is_sret zero, drives fpu_fflags
    //   G3  only memory synchronous exceptions; mispredict / is_mret / is_sret /
    //       fflags zero
    // Zero fields are driven by the FU itself -- the arbiter never fills them in.
    typedef struct packed {
        logic                       result_valid;
        rob_tag_t                   tag_out;
        xlen_t                      result_data;
        logic                       mispredict_flag;
        xlen_t                      mispredict_target_pc;
        logic                       exception_flag;
        logic [EXCP_CAUSE_W-1:0]    exception_cause;
        xlen_t                      exception_tval;
        logic                       is_mret;
        // S9: SRET.  Mutually exclusive with is_mret -- flush_model picks
        // sepc vs mepc from which one is set (FU接入契约 §3.3).
        logic                       is_sret;
        logic [FFLAGS_W-1:0]        fpu_fflags;
    } completion_common_t;

    // ---------------------------------------------------------------------
    // Commit bus -- lane 0 is always head0, lane 1 always head1, no compaction
    // (CompletionScoreboard ④#4)
    // ---------------------------------------------------------------------
    typedef struct packed {
        logic                commit_valid;
        rob_tag_t            commit_tag;
        reg_addr_t           rd_idx;
        logic                rd_is_fp;
        logic                rd_write_enable;
        logic [FFLAGS_W-1:0] commit_fflags;
    } commit_lane_t;

    // ---------------------------------------------------------------------
    // Flush / recovery (CompletionScoreboard ④#3, flush_model ④#1)
    // ---------------------------------------------------------------------
    typedef enum logic [RECOVERY_KIND_W-1:0] {
        RECOVERY_MISPREDICT = 3'd0,
        RECOVERY_EXCEPTION  = 3'd1,
        RECOVERY_MRET       = 3'd2,
        RECOVERY_INTERRUPT  = 3'd3,
        RECOVERY_FENCE_I    = 3'd4,
        // S9.  RECOVERY_KIND_W is 3, so this needs no width change.
        RECOVERY_SRET       = 3'd5
        // 5..7 reserved
    } recovery_kind_e;

    typedef struct packed {
        logic                    valid;
        recovery_kind_e          kind;
        xlen_t                   epc;
        logic [EXCP_CAUSE_W-1:0] cause;
        xlen_t                   tval;
    } trap_state_write_t;

    // ---------------------------------------------------------------------
    // predictor_update -- G0's BRU trains the front-end predictor from the
    // execute stage directly, without waiting for commit (集成层 §1.5).
    // ---------------------------------------------------------------------
    // §1.5 fixes the bundle at {valid, branch_pc(64), actual_taken,
    // actual_target(64), cf_class(2)} and says cf_class comes from exe_subop
    // and carries **no call/return** -- this backend has no RAS.  It does not
    // say what the two bits mean, so the taxonomy is fixed here: the three
    // shapes a predictor actually needs to tell apart, plus a reserved code.
    localparam int CF_CLASS_W = 2;
    typedef enum logic [CF_CLASS_W-1:0] {
        CF_COND_BRANCH = 2'd0,   // BEQ/BNE/BLT/BGE/BLTU/BGEU, C_BEQZ, C_BNEZ
        CF_JUMP_DIRECT = 2'd1,   // JAL, C_J  (C_JAL is RV32-only, not in the frozen pkg)
        CF_JUMP_INDIRECT = 2'd2, // JALR, C_JR, C_JALR
        CF_RESERVED    = 2'd3
    } cf_class_e;

    // Register identity used where integer and FP files must be told apart in
    // one comparison: bit REG_ADDR_W selects the file (0 = INT, 1 = FP).
    localparam int REG_ID_W = REG_ADDR_W + 1;
    typedef logic [REG_ID_W-1:0] reg_id_t;

    function automatic reg_id_t reg_id(input logic is_fp, input reg_addr_t idx);
        return {is_fp, idx};
    endfunction

endpackage

`endif // OR_BE_TYPES_PKG_SV
